name:  Continuous Deployment - Pulumi - Vault

on:
  workflow_call:
    inputs:
      environment:
        description: 'Environment'
        required: true
        type: string
      build_command:
        description: 'Build command'
        required: true
        type: string
    secrets:
      AWS_BASTION_HOST:
        required: true
      SSH_KEY_FOR_BASTION_HOST:
        required: true
      SSH_KEY_FOR_SUBMODULE:
        required: true
      VAULT_ADDR:
        required: true
      VAULT_ROLE_ID:
        required: true
      VAULT_SECRET_ID:
        required: true
      VAULT_SECRET_PULUMI_BASE:
        required: true
      VAULT_SECRET_PULUMI_APP:
        required: true
      VAULT_SECRET_APP:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    env:
      PULUMI_STACK: ${{ inputs.environment }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Checkout Pulumi repository
        run: |
          mkdir $HOME/.ssh
          echo "${{ secrets.SSH_KEY_FOR_SUBMODULE }}" > $HOME/.ssh/id_rsa
          chmod 600 $HOME/.ssh/id_rsa
          git clone git@github.com:Hackmetrix-LLC/pulumi-aws-cloudfront.git ./pulumi-cloudfront
      - name: Connect to Bastion Host for Vault
        run: |
          cd $HOME/.ssh
          ssh-keyscan -H ${{ secrets.AWS_BASTION_HOST }} >> ~/.ssh/known_hosts
          sudo echo "127.0.0.1 ${{ secrets.VAULT_ADDR }}" | sudo tee -a /etc/hosts
          eval `ssh-agent -s`
          ssh-add - <<< "${{ secrets.SSH_KEY_FOR_BASTION_HOST }}"
          ssh -L 8443:${{ secrets.VAULT_ADDR }}:443 -Nf ec2-user@${{ secrets.AWS_BASTION_HOST }}
      - name: Install Vault
        working-directory: /tmp
        run: |
          wget https://releases.hashicorp.com/vault/1.12.3/vault_1.12.3_linux_amd64.zip
          unzip vault_1.12.3_linux_amd64.zip
          sudo mv vault /usr/bin
      - name: Get App Values from Vault
        run: |
          # Get token for vault
          VAULT_TOKEN=$(vault write auth/approle/login role_id="${{ secrets.VAULT_ROLE_ID }}" secret_id="${{ secrets.VAULT_SECRET_ID }}" -format=json |  python -c "import json,sys;obj=json.load(sys.stdin);print(obj['auth']['client_token']);") 
          vault login -no-print token=$VAULT_TOKEN
          # Get envs of secrets of pulumi base
          VAULT_DATA_JSON=$(vault kv get -format=json ${{ secrets.VAULT_SECRET_PULUMI_BASE }} | python -c "import json,sys;obj=json.load(sys.stdin);print(obj['data']['data']);" | sed "s/'/\"/g" | jq .)
          # Inject envs to github action
          echo $VAULT_DATA_JSON | jq -r 'to_entries|map("\(.key)=\(.value|tostring)")|.[]' >> $GITHUB_ENV
          # Export values to file
          echo $VAULT_DATA_JSON | jq -r 'to_entries|map("\(.value|tostring)")|.[]' >> .envs_values
          # Add mask to values of file
          while read value; do
            echo "::add-mask::$value"
          done < .envs_values
          # Get envs of secrets of pulumi app
          VAULT_DATA_JSON=$(vault kv get -format=json ${{ secrets.VAULT_SECRET_PULUMI_APP }} | python -c "import json,sys;obj=json.load(sys.stdin);print(obj['data']['data']);" | sed "s/'/\"/g" | jq .)
          # Inject envs to github action
          echo $VAULT_DATA_JSON | jq -r 'to_entries|map("\(.key)=\(.value|tostring)")|.[]' >> $GITHUB_ENV
          # Export values to file
          echo $VAULT_DATA_JSON | jq -r 'to_entries|map("\(.value|tostring)")|.[]' >> .envs_values
          # Get envs of secrets of app
          VAULT_DATA_JSON=$(vault kv get -format=json ${{ secrets.VAULT_SECRET_APP }} | python -c "import json,sys;obj=json.load(sys.stdin);print(obj['data']['data']);" | sed "s/'/\"/g" | jq .)
          # Inject envs to github action
          echo $VAULT_DATA_JSON | jq -r 'to_entries|map("\(.key)=\(.value|tostring)")|.[]' >> $GITHUB_ENV
        env:
          VAULT_ADDR: https://${{ secrets.VAULT_ADDR }}:8443
      - name: Install Pulumi dependencies
        working-directory: ./pulumi-cloudfront
        run: npm install
      - name: Update Pulumi version
        uses: pulumi/setup-pulumi@v2
        with:
          pulumi-version: 3.60.1
      - name: Install App dependencies
        run: yarn install
      - name: Build App
        run: ${{ inputs.build_command }}
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      - name: Config Pulumi Stack
        working-directory: ./pulumi-cloudfront
        run: |
          pulumi stack select ${{ env.PULUMI_STACK }} --create
          pulumi config set aws:region ${{ env.AWS_REGION }}
        env:
          PULUMI_CONFIG_PASSPHRASE: ${{ env.PULUMI_CONFIG_PASSPHRASE }}
          PULUMI_BACKEND_URL: '${{ env.PULUMI_BACKEND_URL }}'
      - name: Pulumi Refresh
        working-directory: ./pulumi-cloudfront
        if: ${{ env.PULUMI_REFRESH_ENABLED == 'true' }}
        run: pulumi refresh -y --non-interactive
        env:
          PULUMI_CONFIG_PASSPHRASE: ${{ env.PULUMI_CONFIG_PASSPHRASE }}
          PULUMI_BACKEND_URL: '${{ env.PULUMI_BACKEND_URL }}'
      - name: Pulumi Cancel
        working-directory: ./pulumi-cloudfront
        if: ${{ env.PULUMI_CANCEL_ENABLED == 'true' }}
        run: pulumi cancel -y --non-interactive
        env:
          PULUMI_CONFIG_PASSPHRASE: ${{ env.PULUMI_CONFIG_PASSPHRASE }}
          PULUMI_BACKEND_URL: '${{ env.PULUMI_BACKEND_URL }}'
      - name: Deploy Infrastructure
        working-directory: ./pulumi-cloudfront
        run: pulumi up -y --non-interactive --skip-preview
        env:
          ENVIRONMENT: ${{ inputs.environment }}
          PULUMI_CONFIG_PASSPHRASE: ${{ env.PULUMI_CONFIG_PASSPHRASE }}
          PULUMI_BACKEND_URL: '${{ env.PULUMI_BACKEND_URL }}'
